sudo: false
cache: bundler
bundler_args: --retry=3 --jobs=3
language: ruby
rvm:
  - 2.2.2
matrix:
  fast_finish: true
services:
  - redis-server
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
